### ISSUE TITLE
undefined $dir

### ISSUE THREAD

**Issue by tbrowder** [stmuk/rakudup#10]
In the rakudup script, it looks like the “$dir” variable at line 31 is undefined.

**Comment by stmuk** [comment]
fixed by 14ba2b9

**Comment by stmuk** [comment]
Thanks!

**Comment by tbrowder** [comment]
I’ve copied and modified your script to do the same thing for the head of the master branch, and I will use both for my module toaster machine. Thanks for a very useful script!
